# Generated by Django 3.2.6 on 2021-10-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='start_date',
        ),
    ]
